INSERT INTO MATRICULA (CODMATRICULA, RA, CODCURSO, PERLETIVO, DMATRICULA) VALUES (1, 123, 1, '20251', GETDATE())
delete from MATRICULA 

--INSERIR ALUNO
/*teste
TESTE
TeStE
*/

INSERT INTO ALUNO(RA, NOME, DTNASC, ENDERECO, TELEFONE, EMAIL, SEXO) 
VALUES (125, 'MARIA', '1980-11-18', 'RUA DA FATEC', '1299999', 'WBREZOLINO@GMAIL.COM', 'M')

SP_HELP ALUNO --facilita ver informacoes da tabela

SELECT * FROM ALUNO --vizualizar os dados da tabela com os dados

INSERT INTO CURSO (CODCURSO, DESCRICAO) VALUES (1, 'ADS')

SELECT * FROM CURSO
SELECT * FROM ALUNO

DELETE FROM ALUNO WHERE RA = 123

SELECT  ALUNO.RA, ALUNO.NOME, CURSO.DESCRICAO FROM  ALUNO 
INNER JOIN MATRICULA ON ALUNO.RA=MATRICULA.RA --inner join  = junção de chaves, só traz oque está na 
--intersecção, pensando em teoria de conjuntos como ilustração. Se cadastro alguem na tabela aluno e não 
--o matriculo, o inner join não traz.--
INNER JOIN CURSO ON CURSO.CODCURSO=MATRICULA.CODCURSO 

--left pega todos os alunos, estando matriculados ou não, left pesa para a esquerda.--
SELECT  ALUNO.RA, ALUNO.NOME, CURSO.DESCRICAO FROM  ALUNO 
LEFT JOIN MATRICULA ON ALUNO.RA=MATRICULA.RA 
LEFT JOIN CURSO ON CURSO.CODCURSO=MATRICULA.CODCURSO

--WHERE É O FILTRO--
SELECT  ALUNO.RA, ALUNO.NOME, CURSO.DESCRICAO FROM  ALUNO 
LEFT JOIN MATRICULA ON ALUNO.RA=MATRICULA.RA 
LEFT JOIN CURSO ON CURSO.CODCURSO=MATRICULA.CODCURSO
WHERE CURSO.DESCRICAO IS NULL
--BANCO NADA MAIS É DOQUE TEORIA DE CONJUNTOS