-- Tabela de CONVENIOS_MEDICOS
CREATE TABLE CONVENIOS_MEDICOS (
    ID_CONVENIO INT PRIMARY KEY IDENTITY(1,1),
    NOME_CONVENIO VARCHAR(100) UNIQUE NOT NULL
);

-- Tabela de PACIENTES
CREATE TABLE PACIENTES (
    ID_PACIENTE INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(255) NOT NULL,
    RG VARCHAR(20) UNIQUE,
    CPF VARCHAR(11) UNIQUE,
    SEXO CHAR(1),
    DATA_NASCIMENTO DATE,
    TELEFONE VARCHAR(20),
    ID_CONVENIO INT,
    MATRICULA_CONVENIADO VARCHAR(50),
    CONSTRAINT FK_PACIENTE_CONVENIO FOREIGN KEY (ID_CONVENIO) REFERENCES CONVENIOS_MEDICOS(ID_CONVENIO)
);

-- Tabela de ESPECIALIDADES
CREATE TABLE ESPECIALIDADES (
    ID_ESPECIALIDADE INT PRIMARY KEY IDENTITY(1,1),
    NOME_ESPECIALIDADE VARCHAR(100) UNIQUE NOT NULL
);

-- Tabela de MEDICOS
CREATE TABLE MEDICOS (
    ID_MEDICO INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(255) NOT NULL,
    CRM VARCHAR(20) UNIQUE NOT NULL,
    TELEFONE VARCHAR(20),
    ID_ESPECIALIDADE INT NOT NULL,
    CONSTRAINT FK_MEDICO_ESPECIALIDADE FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES ESPECIALIDADES(ID_ESPECIALIDADE)
);

-- Tabela de CONSULTAS
CREATE TABLE CONSULTAS (
    ID_CONSULTA INT PRIMARY KEY IDENTITY(1,1),
    ID_PACIENTE INT NOT NULL,
    ID_MEDICO INT NOT NULL,
    DATA_CONSULTA DATE NOT NULL,
    HORARIO_CONSULTA TIME NOT NULL,
    CONSTRAINT FK_CONSULTA_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
    CONSTRAINT FK_CONSULTA_MEDICO FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO)
);