-- Tabela de CLIENTES
CREATE TABLE CLIENTES (
    ID_CLIENTE INT PRIMARY KEY IDENTITY(1,1),
    NOME_CLIENTE VARCHAR(255) NOT NULL,
    ENDERECO_CLIENTE VARCHAR(255)
);

-- Tabela de VENDEDORES
CREATE TABLE VENDEDORES (
    ID_VENDEDOR INT PRIMARY KEY IDENTITY(1,1),
    CODIGO_VENDEDOR VARCHAR(20) UNIQUE NOT NULL,
    NOME_VENDEDOR VARCHAR(255) NOT NULL
);

-- Tabela de NOTAS_FISCAIS
CREATE TABLE NOTAS_FISCAIS (
    NUMERO_NOTA_FISCAL VARCHAR(20) PRIMARY KEY,
    DATA DATE NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ID_VENDEDOR INT NOT NULL,
    ENDERECO_ENTREGA VARCHAR(255),
    CONSTRAINT FK_NF_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
    CONSTRAINT FK_NF_VENDEDOR FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDORES(ID_VENDEDOR)
);

-- Tabela de PRODUTOS
CREATE TABLE PRODUTOS (
    ID_PRODUTO INT PRIMARY KEY IDENTITY(1,1),
    NOME_PRODUTO VARCHAR(255) UNIQUE NOT NULL
);

-- Tabela de ITENS_NOTA_FISCAL
CREATE TABLE ITENS_NOTA_FISCAL (
    ID_ITEM_NOTA INT PRIMARY KEY IDENTITY(1,1),
    NUMERO_NOTA_FISCAL VARCHAR(20) NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE DECIMAL(10, 2) NOT NULL,
    VALOR_UNITARIO DECIMAL(10, 2) NOT NULL,
    CONSTRAINT FK_ITEM_NF FOREIGN KEY (NUMERO_NOTA_FISCAL) REFERENCES NOTAS_FISCAIS(NUMERO_NOTA_FISCAL),
    CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);