-- Tabela de VEICULOS
CREATE TABLE VEICULOS (
    PLACA VARCHAR(10) PRIMARY KEY,
    COR VARCHAR(50),
    ANO_MODELO INT,
    ANO_FABRICACAO INT,
    MODELO VARCHAR(100),
    FABRICANTE VARCHAR(100),
    CHASSI VARCHAR(100)
);

-- Tabela de PROPRIETARIOS_VEICULOS
CREATE TABLE PROPRIETARIOS_VEICULOS (
    ID_PROPRIETARIO_VEICULO INT PRIMARY KEY IDENTITY(1,1),
    PLACA VARCHAR(10) NOT NULL,
    NOME_PROPRIETARIO VARCHAR(255) NOT NULL,
    HABILITACAO_MOTORISTA VARCHAR(20),
    DATA_INICIO_PROPRIEDADE DATE,
    CONSTRAINT FK_VEICULO_PROPRIETARIO FOREIGN KEY (PLACA) REFERENCES VEICULOS(PLACA)
);
