-- Tabela de FUNCIONARIOS
CREATE TABLE FUNCIONARIOS (
    REGISTRO_FUNCIONARIO VARCHAR(20) PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE,
    ID_CONJUGE INT
);

-- Tabela de CONJUGES
CREATE TABLE CONJUGES (
    ID_CONJUGE INT PRIMARY KEY IDENTITY(1,1),
    NOME_CONJUGE VARCHAR(255),
    DATA_NASCIMENTO_CONJUGE DATE,
    REGISTRO_FUNCIONARIO VARCHAR(20) UNIQUE,
    CONSTRAINT FK_CONJUGE_FUNCIONARIO FOREIGN KEY (REGISTRO_FUNCIONARIO) REFERENCES FUNCIONARIOS(REGISTRO_FUNCIONARIO)
);

-- Adicionando a chave estrangeira de CONJUGE em FUNCIONARIOS após a criação da tabela CONJUGES
ALTER TABLE FUNCIONARIOS
ADD CONSTRAINT FK_FUNCIONARIO_CONJUGE FOREIGN KEY (ID_CONJUGE) REFERENCES CONJUGES(ID_CONJUGE);

-- Tabela de FILHOS
CREATE TABLE FILHOS (
    ID_FILHO INT PRIMARY KEY IDENTITY(1,1),
    REGISTRO_FUNCIONARIO VARCHAR(20) NOT NULL,
    NOME_FILHO VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO_FILHO DATE,
    CONSTRAINT FK_FILHO_FUNCIONARIO FOREIGN KEY (REGISTRO_FUNCIONARIO) REFERENCES FUNCIONARIOS(REGISTRO_FUNCIONARIO)
);