CREATE TABLE ALUNO (
	RA INT PRIMARY KEY IDENTITY(1,1),
	NOME NVARCHAR(200),
	EMAIL NVARCHAR(150),
	TELEFONE NVARCHAR(20))

INSERT INTO ALUNO VALUES
('WARNER', 'WBREZOLIN@GMAIL.COM', '121212'),
('FEICHAS', 'FEICHAS@GMAIL.COM', '33333'),
('CHARLES', 'CHARLES@GMAIL.COM', '88888')

CREATE TABLE PESSOA (
	NOME NVARCHAR(200))

INSERT INTO PESSOA (NOME)
SELECT NOME FROM ALUNO

SELECT * FROM PESSOA

CREATE TABLE CURSO (
CODCURSO INT PRIMARY KEY IDENTITY(1,1),
DESCRICAO NVARCHAR(200))

INSERT INTO CURSO VALUES
('ADS'), ('GPI'), ('GH')

CREATE TABLE MATRICULA (
CODMAT INT PRIMARY KEY IDENTITY(1,1),
RA INT,
CODCURSO INT,
CONSTRAINT FK_RA FOREIGN KEY (RA) REFERENCES ALUNO(RA),
CONSTRAINT FK_CC FOREIGN KEY (CODCURSO) REFERENCES CURSO(CODCURSO))

INSERT INTO MATRICULA VALUES
(1,1), (2,1), (3,2), (1,2), (2,3), (3,1)



SELECT * FROM ALUNO
SELECT * FROM CURSO
SELECT * FROM MATRICULA

SELECT ALUNO.RA, ALUNO.NOME, CURSO.DESCRICAO FROM ALUNO
	INNER JOIN MATRICULA ON ALUNO.RA=MATRICULA.RA
	INNER JOIN CURSO ON CURSO.CODCURSO=MATRICULA.CODCURSO

SELECT CURSO.DESCRICAO, COUNT(ALUNO.RA) AS QTD FROM ALUNO
	INNER JOIN MATRICULA ON ALUNO.RA=MATRICULA.RA
	INNER JOIN CURSO ON CURSO.CODCURSO=MATRICULA.CODCURSO
GROUP BY CURSO.DESCRICAO

SELECT C.DESCRICAO, COUNT(A.RA) AS QTD FROM ALUNO A
	INNER JOIN MATRICULA AS M ON A.RA=M.RA
	INNER JOIN CURSO C ON C.CODCURSO=M.CODCURSO
GROUP BY C.DESCRICAO
HAVING COUNT(A.RA) > 1

SELECT TOP 2 C.DESCRICAO, COUNT(A.RA) AS QTD FROM ALUNO A
	INNER JOIN MATRICULA AS M ON A.RA=M.RA
	INNER JOIN CURSO C ON C.CODCURSO=M.CODCURSO
WHERE
	C.DESCRICAO LIKE '%A%'
GROUP BY C.DESCRICAO
ORDER BY 2 DESC

SELECT * FROM ALUNO 
WHERE RA=2

SELECT * FROM ALUNO 
WHERE NOME LIKE ('%SILVA%')

SELECT * FROM ALUNO
WHERE RA IN (1, 3)

SELECT * FROM ALUNO	
WHERE RA > 1 AND RA <=3

SELECT * FROM ALUNO	
WHERE RA BETWEEN 2 AND 3

SELECT * FROM ALUNO
WHERE RA=1 OR NOME='FEICHAS'

SELECT * FROM ALUNO 
WHERE NOME NOT LIKE ('%R%')

SELECT * FROM ALUNO
WHERE RA NOT IN (1, 3)



SELECT C.DESCRICAO, COUNT(A.RA) AS QTD,
CASE WHEN COUNT(A.RA) >= 5 THEN 'ABRE'
	 WHEN COUNT(A.RA) > 2 THEN 'PENSANDO'
	 WHEN COUNT(A.RA) <= 2 THEN 'NÃO ABRE'
END AS STATUS
FROM ALUNO A
	INNER JOIN MATRICULA AS M ON A.RA=M.RA
	INNER JOIN CURSO C ON C.CODCURSO=M.CODCURSO
GROUP BY C.DESCRICAO


CREATE TABLE FUNCIONARIO (
CODFUNC INT PRIMARY KEY IDENTITY(1,1),
NOME NVARCHAR(200))

CREATE TABLE DEPENDENTE (
CODDEP INT PRIMARY KEY IDENTITY(1,1),
NOMEDEP NVARCHAR(200),
CODFUNC INT,
CONSTRAINT FK_CF FOREIGN KEY (CODFUNC) REFERENCES FUNCIONARIO(CODFUNC))

INSERT INTO FUNCIONARIO VALUES
('WARNER'), ('FEICHAS'), ('CHARLES')

INSERT INTO DEPENDENTE VALUES
('BEATRIZ 2', 2)

SELECT * FROM  FUNCIONARIO F
LEFT JOIN DEPENDENTE D ON F.CODFUNC=D.CODFUNC


SELECT F.NOME, COUNT(D.CODDEP) FROM  FUNCIONARIO F
LEFT JOIN DEPENDENTE D ON F.CODFUNC=D.CODFUNC
GROUP BY F.NOME